### PR TITLE
ping: fix flaky test

### LINKED ISSUE #1616: flaky TestPing
```
  === RUN   TestPing
  2022/06/24 14:44:29 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
      ping_test.go:47: ping took:  43.4µs
      ping_test.go:47: ping took:  8.205732ms
      ping_test.go:47: ping took:  107.001µs
      ping_test.go:47: ping took:  77.8µs
      ping_test.go:47: ping took:  66.3µs
      ping_test.go:46: 
          	Error Trace:	ping_test.go:46
          	            				ping_test.go:35
          	Error:      	Received unexpected error:
          	            	Write on stream 5 canceled with error code 0
          	Test:       	TestPing
  --- FAIL: TestPing (0.10s)

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1616.

If we end up with 2 connections (TCP and QUIC) between the nodes, the dialing node might close one of those connection.
This will cause a stream reset on the connection that the dialed node might have chosen for its ping stream.

### CODE REVIEW

File: p2p/protocol/ping/ping_test.go [hunk 1]
```diff
@@ -5,26 +5,29 @@ import (
...
 	require.NoError(t, err)
+	defer h1.Close()
 	h2, err := bhost.NewHost(swarmt.GenSwarm(t), nil)
 	require.NoError(t, err)
+	defer h2.Close()
 
 	err = h1.Connect(ctx, peer.AddrInfo{
 		ID:    h2.ID(),
-		Addrs: h2.Addrs(),
+		Addrs: []ma.Multiaddr{h2.Addrs()[0]},
```
Comment (MarcoPolo) [inline p2p/protocol/ping/ping_test.go:30]: Is there a change we can do that does this at a higher level? I think we see this flakiness in other tests too.

Comment (marten-seemann) [reply p2p/protocol/ping/ping_test.go:30]: True, this is not the first time I'm submitting a patch like this.

At which level would you suggest to do it?

**Review by MarcoPolo — APPROVED** [review]
