### PR TITLE
identify: fix flaky tests

### LINKED ISSUE #1497: flaky TestIdentifyDeltaOnProtocolChange
```
  === RUN   TestIdentifyDeltaOnProtocolChange
      id_test.go:409: 
          	Error Trace:	id_test.go:409
          	Error:      	Condition never satisfied
          	Test:       	TestIdentifyDeltaOnProtocolChange
  --- FAIL: TestIdentifyDeltaOnProtocolChange (1.15s)

### PR DESCRIPTION
**Pull request by MarcoPolo**
Fixes #1497 by removing the sleeps/waits. In general, sleeps will cause flakiness in CI so anyway we can completely avoid them will let our tests be more resilient to exogenous performance impacts.

This doesn't remove all the sleeps in this file. But if this looks good I can remove the other cases as well.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
@marten-seemann instrumented multiplexer is removed from this PR

File: p2p/protocol/identify/id_test.go [hunk 1]
```diff
@@ -401,43 +416,60 @@ func TestIdentifyDeltaOnProtocolChange(t *testing.T) {
...
 		}
+		close(waitForDelta)
+	}()
 
-		_, okfoo := have["foo"]
-		_, okbar := have["bar"]
-		return okfoo && !okbar
-	}, time.Second, 10*time.Millisecond)
+	// check that h1 now has forgotten about h2's bar protocol.
+	recvWithTimeout(t, waitForDelta, 10*time.Second, "timed out waiting for protocol to be removed")
```
Comment (marten-seemann) [inline p2p/protocol/identify/id_test.go:464]: I wish `require` had a function for this.

File: p2p/protocol/identify/id_test.go [hunk 2]
```diff
@@ -356,7 +356,7 @@ func TestIdentifyDeltaOnProtocolChange(t *testing.T) {
 	defer cancel()
 
 	h1 := blhost.NewBlankHost(swarmt.GenSwarm(t))
-	h2 := blhost.NewBlankHost(swarmt.GenSwarm(t))
+	h2 := blhost.NewBlankHost(swarmt.GenSwarm(t, swarmt.OptDisableQUIC))
```
Comment (marten-seemann) [inline p2p/protocol/identify/id_test.go:359]: What's the reason we're disabling QUIC? Are there any problems with parallel connections?

File: p2p/protocol/identify/id_test.go [hunk 3]
```diff
@@ -401,43 +416,60 @@ func TestIdentifyDeltaOnProtocolChange(t *testing.T) {
 	}
 	defer sub.Close()
 
+	// Channels that watch the stream mux for when these bytes are read.
+	h1ProtocolsUpdates, err := h1.EventBus().Subscribe(&event.EvtPeerProtocolsUpdated{}, eventbus.BufSize(2))
```
Comment (marten-seemann) [inline p2p/protocol/identify/id_test.go:420]: Here too?

File: p2p/protocol/identify/id_test.go (hunk 2 above)
Comment (MarcoPolo) [reply p2p/protocol/identify/id_test.go]: No, I disabled it to inspect the bytes on the wire. This is a remnant of that

**Review by marten-seemann — APPROVED** [review]
