### PR TITLE
fix: return the best _acceptable_ conn in NewStream

### LINKED ISSUE #1603: Connect should wait for an acceptable connection
Currently, it waits for _any_ connection, then returns. Unfortunately, this means that if the user calls `host.NewStream(peer)` to try to get a new stream to a non-connected peer, we'll _fail_ every single time if we try to create a stream behind a NAT.

The difficulty here is that we aren't "in control", and don't know if the remote peer will actually directly connect to us. It's up to the _receiver_ to establish a direct connection.

I think the solution here is to wait a bit after we establish a transient connection to see if a non-transient connection comes through. The tricky part will be actually _implementing_ that...

### PR DESCRIPTION
**Pull request by Stebalien**
Otherwise, we can return, e.g., a transient connection that can't actually be used.

I noticed bitswap was trying to use transient connections, which shouldn't be possible. To really fix this issue, we'd also need to fix #1603 as well, but that's harder.

### CODE REVIEW

**Comment by marten-seemann** [comment]
Not sure I understand the swarm code correctly. Let's assume we only have a transient conn to a peer. We will therefore call `dialPeer`: https://github.com/libp2p/go-libp2p/blob/884028550c9b4d1d0b1090aaf18e087bff3fa8bf/p2p/net/swarm/swarm.go#L354-L369

`dialPeer` will then start a new dial sync (there are currently no active dials), as we only have a transient conn: https://github.com/libp2p/go-libp2p/blob/884028550c9b4d1d0b1090aaf18e087bff3fa8bf/p2p/net/swarm/swarm_dial.go#L251-L264

Does that mean we'll end up with two transient connections now?

**Comment by Stebalien** [comment]
Ah.... ok, this is all broken.

**Comment by Stebalien** [comment]
Ok, it's "fixed". Horribly broken, but at least it's correct.

File: p2p/net/swarm/swarm.go [hunk 1]
```diff
@@ -447,15 +451,26 @@ func (s *Swarm) bestConnToPeer(p peer.ID) *Conn {
...
-			return conn
-		}
+	if conn == nil {
+		return nil, nil
 	}
-	return nil
+
+	forceDirect, _ := network.GetForceDirectDial(ctx)
+	if forceDirect && !isDirectConn(conn) {
+		return nil, nil
```
Comment (MarcoPolo) [inline p2p/net/swarm/swarm.go:465]: What happens here? We may have a transient connection but we'll try to dial again?

**Review by MarcoPolo — COMMENTED** [review]
It's a bit confusing that we have two different concepts of "transient" connections in go-libp2p. Transient as in a limited connection over a relay and transient as in a connection that hasn't been upgraded yet and doesn't have a peerid associated with it yet.

File: p2p/net/swarm/swarm.go (hunk 1 above)
Comment (Stebalien) [reply p2p/net/swarm/swarm.go:465]: Yes. We need to do that for hole-punching.

**Review by MarcoPolo — APPROVED** [review]

**Review by marten-seemann — APPROVED** [review]
