### PR TITLE
fix: Add wrapped error type in `stream.go`

### LINKED ISSUE #3156: Return wrapped `network.ErrReset` error type with more info
Right now we replace specific stream errors with `network.ErrReset` ([example](https://github.com/libp2p/go-libp2p/blob/fde0e3a487fc18fc22eb5dfc97d81572b79b5d95/p2p/transport/webtransport/stream.go#L40)). We should instead return a new error type that unwraps to a  `network.ErrReset` with a [`.Unwrap() []error` method](https://pkg.go.dev/errors) and includes addition error information gleaned from the transport. This is at least a problem in the WebTransport and QUIC transports. Note that we probably want the multi-error return version and return both a network.ErrReset and the underlying stream error.

### PR DESCRIPTION
**Pull request by Prabhat1308**
fixes #3156

### CODE REVIEW

**Review by sukunrt — CHANGES_REQUESTED** [review]
Can we just use: 
`StreamError` from:

https://github.com/libp2p/go-libp2p/blob/master/core/network/mux.go#L17

**Comment by sukunrt** [comment]
You can just use the remote field on `webtransport.StreamError`

File: p2p/transport/webtransport/stream.go [hunk 1]
```diff
@@ -37,15 +37,29 @@ var _ network.MuxedStream = &stream{}
...
 	if err != nil && errors.Is(err, &webtransport.StreamError{}) {
-		err = network.ErrReset
+		var streamErr *webtransport.StreamError
+		if errors.As(err, &streamErr) {
+			err = &network.StreamError{
+				ErrorCode:      0,
+				Remote:         streamErr.Remote,
+				TransportError: streamErr,
+			}
+		}
```
Comment (sukunrt) [inline p2p/transport/webtransport/stream.go:62]: Does this work? 
```
if err != nil {
    var streamErr *webtransport.StreamError
    if errors.As(err, &streamErr) {
        err = &network.StreamError {...}
    }
}
```

We avoid the traversing the error chain twice with both `errors.Is` and `errors.As`.

File: p2p/transport/webtransport/stream.go [hunk 2]
```diff
@@ -37,15 +37,29 @@ var _ network.MuxedStream = &stream{}
 func (s *stream) Read(b []byte) (n int, err error) {
 	n, err = s.Stream.Read(b)
 	if err != nil && errors.Is(err, &webtransport.StreamError{}) {
-		err = network.ErrReset
+		var streamErr *webtransport.StreamError
+		if errors.As(err, &streamErr) {
+			err = &network.StreamError{
+				ErrorCode:      0,
+				Remote:         streamErr.Remote,
+				TransportError: streamErr,
```
Comment (sukunrt) [inline p2p/transport/webtransport/stream.go:45]: Should be `err`. We want the complete / unparsed / wrapped error in TransportError.

File: p2p/transport/webtransport/stream.go (hunk 1 above)
Comment (Prabhat1308) [reply p2p/transport/webtransport/stream.go]: Ahh missed this. Fixed !

File: p2p/transport/webtransport/stream.go (hunk 2 above)
Comment (Prabhat1308) [reply p2p/transport/webtransport/stream.go]: fixed.

**Review by sukunrt — APPROVED** [review]

**Comment by sukunrt** [comment]
Thanks @Prabhat1308

**Review by MarcoPolo — APPROVED** [review]
