### PR TITLE
pstoremanager: fix test timeout

### LINKED ISSUE #1585: pstoremanager: test timeout
```
panic: test timed out after 10m0s
  
  goroutine 50 [running]:
  testing.(*M).startAlarm.func1()
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1788 +0x8e
  created by time.goFunc
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/time/sleep.go:180 +0x31
  
  goroutine 1 [chan receive, 9 minutes]:
  testing.tRunner.func1()
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1225 +0x311
  testing.tRunner(0xc000102b60, 0xc0001d1ce0)
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1265 +0x13b
  testing.runTests(0xc00099a280, {0x5356b40, 0x3, 0x3}, {0x408c0ad, 0x1a, 0x55e34e0})
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1596 +0x43f
  testing.(*M).Run(0xc00099a280)
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1504 +0x51d
  main.main()
  	_testmain.go:651 +0x20a
  
  goroutine 42 [chan receive, 10 minutes]:
  github.com/libp2p/go-libp2p/p2p/host/pstoremanager_test.TestClose(0xc000102d00)
  	/Users/runner/work/go-libp2p/go-libp2p/p2p/host/pstoremanager/pstoremanager_test.go:97 +0x3c5
  testing.tRunner(0xc000103[380](https://github.com/libp2p/go-libp2p/runs/6681155337?check_suite_focus=true#step:7:382), 0x4bb25f0)
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1259 +0x102
  created by testing.(*T).Run
  	/Users/runner/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1306 +0x35a
  FAIL	github.com/libp2p/go-libp2p/p2p/host/pstoremanager	600.587s

### PR DESCRIPTION
**Pull request by MarcoPolo**
Fixes #1585 by actually making sure the event is sent before we close, instead of waiting and expecting the event to be sent by then.

### CODE REVIEW

File: p2p/host/pstoremanager/pstoremanager_test.go [hunk 1]
```diff
@@ -86,11 +86,18 @@ func TestClose(t *testing.T) {
...
+	require.NoError(t, err)
+
 	require.NoError(t, emitter.Emit(event.EvtPeerConnectednessChanged{
 		Peer:          "foobar",
 		Connectedness: network.NotConnected,
 	}))
-	time.Sleep(10 * time.Millisecond) // make sure the event is sent before we close
+
+	// make sure the event is sent before we close
+	<-sub.Out()
```
Comment (marten-seemann) [inline p2p/host/pstoremanager/pstoremanager_test.go:99]: Should we have a select with a timeout here?

Comment (marten-seemann) [reply p2p/host/pstoremanager/pstoremanager_test.go]: Also don’t feel strongly. I generally prefer it because the error message is nicer.

**Review by marten-seemann — APPROVED** [review]
