### PR TITLE
fix: don't prefer local ports from other addresses when dialing

### LINKED ISSUE #1611: flaky TestGlobalPreferenceV4 on Ubuntu
https://github.com/libp2p/go-libp2p/runs/7028901565?check_suite_focus=true
```
  === RUN   TestGlobalPreferenceV4
      transport_test.go:140: when listening on /ip4/127.0.0.1/tcp/0, should prefer /ip4/127.0.0.1/tcp/0 over /ip4/10.1.1.88/tcp/0
      transport_test.go:142: when listening on /ip4/127.0.0.1/tcp/0, should prefer /ip4/0.0.0.0/tcp/0 over /ip4/10.1.1.88/tcp/0
      transport_test.go:180: dialed /ip4/127.0.0.1/tcp/46587 from 127.0.0.1:60340. expected to dial from port [45733]
      transport_test.go:193: dialed /ip4/127.0.0.1/tcp/46587 from 127.0.0.1:60344. expected to dial from port [45733]
      transport_test.go:145: when listening on /ip4/10.1.1.88/tcp/0, should prefer /ip4/0.0.0.0/tcp/0 over /ip4/127.0.0.1/tcp/0

### PR DESCRIPTION
**Pull request by Stebalien**
This address may already be in-use (on that other address) somewhere else.

Thanks to @schomatis for figuring this out.

fixes #1611

### CODE REVIEW

File: p2p/net/reuseport/dialer.go [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+}
+
+// DialContext dials a target addr.
+// Dialing preference is
+// * If there is a listener on the local interface the OS expects to use to route towards addr, use that.
+// * If there is a listener on a loopback address, addr is loopback, use that.
+// * If there is a listener on an undefined address (0.0.0.0 or ::), use that.
+// * Otherwise, dial with a random port on the unspecified address.
+func (d *dialer) DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
+	if len(d.specific) > 0 || len(d.loopback) > 0 {
```
Comment (Stebalien) [inline p2p/net/reuseport/dialer.go:36]: Because users _usually_ just listen on the all address, and we can avoid double-resolving the TCP addr in that case.

File: p2p/net/reuseport/dialer.go [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+		tcpAddr, err := net.ResolveTCPAddr(network, addr)
+		if err != nil {
+			return nil, err
+		}
+		ip := tcpAddr.IP
+		if !ip.IsLoopback() && !ip.IsGlobalUnicast() {
+			return nil, fmt.Errorf("undialable IP: %s", ip)
+		}
+
+		if len(d.specific) > 0 {
```
Comment (Stebalien) [inline p2p/net/reuseport/dialer.go:46]: Looking up routes in netroute is currently rather expensive. Let's avoid that if we can.

File: p2p/net/reuseport/transport_test.go [hunk 3]
```diff
@@ -177,20 +176,13 @@ func testPrefer(t *testing.T, listen, prefer, avoid ma.Multiaddr) {
 	}
 	defer listenerB1.Close()
 
-	dialOne(t, &trB, listenerA, listenerB1.Addr().(*net.TCPAddr).Port)
```
Comment (Stebalien) [inline p2p/net/reuseport/transport_test.go:180]: We now _only_ prefer source ports if the dialing addresses match.

File: p2p/net/reuseport/dial.go [hunk 4]
```diff
@@ -2,18 +2,11 @@ package reuseport
...
 
-	"github.com/libp2p/go-reuseport"
 	ma "github.com/multiformats/go-multiaddr"
 	manet "github.com/multiformats/go-multiaddr/net"
 )
 
-type dialer interface {
-	Dial(network, addr string) (net.Conn, error)
-	DialContext(ctx context.Context, network, addr string) (net.Conn, error)
-}
```
Comment (Stebalien) [inline p2p/net/reuseport/dial.go:15]: We now have one dialer, so there's no need to abstract over them.

**Comment by schomatis** [comment]
CI error is likely https://github.com/libp2p/go-libp2p/issues/1421 (working on it in https://github.com/libp2p/go-libp2p/pull/1659 but need more input).

File: p2p/net/reuseport/dialer.go (hunk 1 above)
Comment (marten-seemann) [reply p2p/net/reuseport/dialer.go:36]: Can you add this as a comment? Also, I'm not sure I understand it. If the user listens on all the addresses, which one will be `> 0`?

File: p2p/net/reuseport/dialer.go (hunk 2 above)
Comment (marten-seemann) [reply p2p/net/reuseport/dialer.go:46]: This too?

File: p2p/net/reuseport/dialer.go [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+func randAddr(addrs []*net.TCPAddr) *net.TCPAddr {
+	if len(addrs) > 0 {
+		return addrs[rand.Intn(len(addrs))]
+	}
+	return nil
+}
+
+// DialContext dials a target addr.
+// Dialing preference is
+// * If there is a listener on the local interface the OS expects to use to route towards addr, use that.
```
Comment (marten-seemann) [inline p2p/net/reuseport/dialer.go:31]: I have problems parsing this sentence.

File: p2p/net/reuseport/dialer.go [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+// * If there is a listener on a loopback address, addr is loopback, use that.
```
Comment (marten-seemann) [inline p2p/net/reuseport/dialer.go:32]: This one as well, do you mean?
```suggestion
// * If there is a listener on a loopback address and addr is loopback, use that.
```

File: p2p/net/reuseport/dialer.go [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+	"math/rand"
+	"net"
+
+	"github.com/libp2p/go-netroute"
+)
+
+type dialer struct {
+	specific    []*net.TCPAddr
+	loopback    []*net.TCPAddr
+	unspecified []*net.TCPAddr
```
Comment (marten-seemann) [inline p2p/net/reuseport/dialer.go:15]: Can you add a comment here what kind of addresses would land in `specific` and in `unspecified`?

**Review by marten-seemann — COMMENTED** [review]
I remember having spent quite some time digging through this code a while back (and forgotten most about it), so I'm mainly asking for more documentation here.

**Comment by Stebalien** [comment]
@marten-seemann done.

**Review by marten-seemann — APPROVED** [review]
Thank you for the excellent documentation, @Stebalien!
