### PR TITLE
webtransport: fix flaky accept queue test

### LINKED ISSUE #1870: webtransport: flaky TestAcceptQueueFilledUp
```
=== RUN   TestAcceptQueueFilledUp
    transport_test.go:539: 
        	Error Trace:	/home/runner/work/go-libp2p/go-libp2p/p2p/transport/webtransport/transport_test.go:539
        	Error:      	Received unexpected error:
        	            	error reading handshake message: stream reset, but failed to convert stream error 386759528: error code outside of expected range
        	Test:       	TestAcceptQueueFilledUp
--- FAIL: TestAcceptQueueFilledUp (10.04s)

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1870. 

The problem here is that it's not valid assumption that the 16 connection we dial first are all accepted (by the QUIC listener) in that order.
What we should assert that out of 17 connections dialed, 16 are accepted and 1 is rejected.

### CODE REVIEW

File: p2p/transport/webtransport/transport_test.go [hunk 1]
```diff
@@ -473,17 +473,29 @@ func TestAcceptQueueFilledUp(t *testing.T) {
...
 	}
 
-	conn, err := newConn()
-	if err == nil {
-		_, err = conn.AcceptStream()
-	}
-	require.Error(t, err)
+	// Since the handshakes complete asynchronously, we won't know _which_ one is rejected,
+	// so the only thing we can test for is that exactly one connection attempt is rejected.
+	require.Eventually(t, func() bool { return len(errChan) > 0 }, time.Second, 10*time.Millisecond, "expected an error to occur")
```
Comment (MarcoPolo) [inline p2p/transport/webtransport/transport_test.go:493]: Can we recv from this channel with a timeout instead of polling?

File: p2p/transport/webtransport/transport_test.go [hunk 2]
```diff
@@ -473,17 +473,29 @@ func TestAcceptQueueFilledUp(t *testing.T) {
...
+	require.Never(t, func() bool { return len(errChan) > 1 }, 100*time.Millisecond, 10*time.Millisecond, "only expected one error to occur")
```
Comment (MarcoPolo) [inline p2p/transport/webtransport/transport_test.go:494]: Can we recv with timeout here as well

File: p2p/transport/webtransport/transport_test.go [hunk 3]
```diff
@@ -473,17 +473,29 @@ func TestAcceptQueueFilledUp(t *testing.T) {
...
+
+	// test shutdown
+	require.NoError(t, ln.Close())
+	require.Eventually(t, func() bool { return len(errChan) == num }, time.Second, 10*time.Millisecond)
```
Comment (MarcoPolo) [inline p2p/transport/webtransport/transport_test.go:498]: Same here

**Review by MarcoPolo — APPROVED** [review]
Looks good, but I think would be nice to use receives insteads

File: p2p/transport/webtransport/transport_test.go (hunk 1 above)
Comment (marten-seemann) [reply p2p/transport/webtransport/transport_test.go:493]: Makes sense.

File: p2p/transport/webtransport/transport_test.go (hunk 2 above)
Comment (marten-seemann) [reply p2p/transport/webtransport/transport_test.go:494]: Yes.
