### PR TITLE
fix natManager to close natManager.nat

### LINKED ISSUE #1449: NATManager should close nmgr.nat
libp2p v0.19.0

When NATManager is closed it does not closes nmgr.nat:
https://github.com/libp2p/go-libp2p/blob/5151d4b4faaae04523dd83b9377881fbc717c752/p2p/host/basic/natmgr.go#L65-L69

When resolving this issue look at #1448, not to fall in the same pitfall

### PR DESCRIPTION
**Pull request by watjurk**
This PR fixes #1449

### CODE REVIEW

File: p2p/host/basic/natmgr.go [hunk 1]
```diff
@@ -65,7 +65,13 @@ func newNatManager(net network.Network) *natManager {
 func (nmgr *natManager) Close() error {
 	nmgr.ctxCancel()
 	nmgr.refCount.Wait()
-	return nil
+	var err error
+	nmgr.natMx.Lock()
+	if nmgr.nat != nil {
+		err = nmgr.nat.Close()
+	}
+	nmgr.natMx.Unlock()
```
Comment (Stebalien) [inline p2p/host/basic/natmgr.go:73]: We should do this in a defer in `background()`. That way we can be sure it only happens once.

File: p2p/host/basic/natmgr.go [hunk 2]
```diff
@@ -37,7 +37,7 @@ func NewNATManager(net network.Network) NATManager {
 //  * closing the natManager closes the nat and its mappings.
 type natManager struct {
 	net   network.Network
-	natmu sync.RWMutex
+	natMx sync.RWMutex
```
Comment (Stebalien) [inline p2p/host/basic/natmgr.go:40]: Let's leave the name (`mu` stands for `mutex` and is a pretty common suffix in go).

**Review by Stebalien — CHANGES_REQUESTED** [review]
Thanks!

File: p2p/host/basic/natmgr.go (hunk 1 above)
Comment (watjurk) [reply p2p/host/basic/natmgr.go:73]: Are you saying that someone could call Close many times? In my opinion this would be incorrect.

File: p2p/host/basic/natmgr.go (hunk 2 above)
Comment (watjurk) [reply p2p/host/basic/natmgr.go:40]: I've renamed it because in holepuncher we use "Mx".
https://github.com/libp2p/go-libp2p/blob/f383f4681f75b004ec2da0f4e9df0983bfbc65d2/p2p/protocol/holepunch/holepuncher.go#L36-L53

File: p2p/host/basic/natmgr.go (hunk 1 above)
Comment (Stebalien) [reply p2p/host/basic/natmgr.go:73]: People often `defer thing.Close()`. It should usually be idempotent.

File: p2p/host/basic/natmgr.go (hunk 2 above)
Comment (Stebalien) [reply p2p/host/basic/natmgr.go:40]: Ah, I see. Eh, that's fine.

File: p2p/host/basic/natmgr.go (hunk 1 above)
Comment (watjurk) [reply p2p/host/basic/natmgr.go:73]: But doing this (closing it more than one) here should not be a problem, firstly `nmgr.nat.Close()` is idempotent, secondly by moving this to a deferred function in `background()` we lose the ability to return the error from `nmgr.nat.Close()`.

Comment (MarcoPolo) [reply p2p/host/basic/natmgr.go:73]: Generally I agree that these child objects should be closed when the parent is closed directly.

However, the current code already follows a pattern of _background worker + context cancel for cleanup_ so this change should follow the conventions of the current code rather than introducing a new pattern. If that makes sense, @watjurk, could you please move this to a defer in the background instead?

**Review by MarcoPolo — CHANGES_REQUESTED** [review]
Please move close logic to defer in background. Thank you!

**Review by MarcoPolo — APPROVED** [review]
Thank you!
