### PR TITLE
transport.Listener,quic: Support multiple QUIC versions with the same Listener. Only return a single multiaddr per listener.

### LINKED ISSUE #1904: quic: QUIC listener doesn't respect the QUIC version of the listen address
```go
func TestListenOnlyOnOneVersion(t *testing.T) {
	t.Run("only one draft-29", func(t *testing.T) {
		h1, err := libp2p.New(
			libp2p.Transport(libp2pquic.NewTransport),
			libp2p.ListenAddrStrings(
				"/ip4/127.0.0.1/udp/12345/quic", // QUIC draft-29
			),
		)
		require.NoError(t, err)
		defer h1.Close()

		addrs := h1.Addrs()
		require.Len(t, addrs, 1)
		require.Equal(t, ma.P_QUIC, getQUICMultiaddrCode(addrs[0]))
	})
}
```

This test fails, as the listener is listening on both versions.

### PR DESCRIPTION
**Pull request by MarcoPolo**
Fixes #1904

Undoes part of the work in https://github.com/libp2p/go-libp2p/pull/1881. The QUIC transport now returns a virtual listener that only handles one QUIC version. If a user then listens on another QUIC version with the same multiaddr, we return another virtual listener that uses the same underlying listener but only advertises the other QUIC version.

This is ready for review, but I see some flakiness in the tests (maybe also from #1905 ) so I'll continue debugging that.

### CODE REVIEW

File: p2p/transport/quic/virtuallistener.go [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+}
+
+type acceptLoopRunner struct {
+	listenerMu sync.Mutex
+
+	muxerMu sync.Mutex
+	muxer   map[quic.VersionNumber]chan acceptVal
+}
+
+func (r *acceptLoopRunner) acceptForVersion(v quic.VersionNumber) chan acceptVal {
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:88]: Nit: `AcceptForVersion`. Makes it easier to spot that this is called from outside this struct.

File: p2p/transport/quic/virtuallistener.go [hunk 2]
```diff
@@ -0,0 +1,168 @@
...
+
+	if _, ok := r.muxer[v]; ok {
+		panic("unexpected chan already found in accept muxer")
+	}
+
+	r.muxer[v] = ch
+	return ch
+}
+
+func (r *acceptLoopRunner) rmAcceptForVersion(v quic.VersionNumber) {
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:102]: Same here.

File: p2p/transport/quic/virtuallistener.go [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+	return v.conn, v.err
+}
+
+type acceptVal struct {
+	conn tpt.CapableConn
+	err  error
+}
+
+type acceptLoopRunner struct {
+	listenerMu sync.Mutex
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:82]: Why is this mutex needed? I assume it's to protect against concurrent calls to `Accept` from multiple listeners? If so, I'd prefer to call this a semaphore (and make it a `sem chan struct` with cap 1).

File: p2p/transport/quic/virtuallistener.go [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+
+func (l *virtualListener) Accept() (tpt.CapableConn, error) {
+	var v acceptVal
+	var ok bool
+	select {
+	// Check if we have a pending connection first
+	case v, ok = <-l.acceptChan:
+	default:
+		// No? Let's call Accept and wait for a connection
+		go l.acceptRunnner.Accept(l.listener, l.version)
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:66]: Not sure I understand this logic here, especially the pending first connection.

I was wondering if `Accept` could this be driven by the Go routines that called `Accept`? It would be really nice if we didn't have to start another Go routine here. 
You could then retrieve connections from the underlying listener, and return them directly (if they're intended for this virtual listener), or enqueue them (if they're intended for a virtual listener of a different version).

Comment (MarcoPolo) [reply p2p/transport/quic/virtuallistener.go]: Refactored to get rid of the goroutine. We still check first if we have previously enqueued a connection.

File: p2p/transport/quic/virtuallistener.go [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+		err = l.listener.Close()
+		delete(l.t.listeners, l.udpAddr)
+		return err
+	}
+
+	for i := 0; i < len(listeners); i++ {
+		// Swap remove
+		if l == listeners[i] {
+			listeners[i] = listeners[len(listeners)-1]
+			listeners = listeners[0 : len(listeners)-1]
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:50]:
```suggestion
			listeners = listeners[:len(listeners)-1]
```

File: p2p/transport/quic/virtuallistener.go [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+		// Nothing to handle this connection version. Close it
+		conn.Close()
+		return nil, nil
+	}
+
+	// Non blocking
+	select {
+	case ch <- acceptVal{conn: conn}:
+	default:
+		// We dropped the connection, close it
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:160]:
```suggestion
		// accept queue filled up, drop the connection
```

Comment (marten-seemann) [reply p2p/transport/quic/virtuallistener.go:160]: Can you also add a log line here?

File: p2p/transport/quic/virtuallistener.go [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+var _ tpt.Listener = &virtualListener{}
+
+func (l *virtualListener) Multiaddr() ma.Multiaddr {
+	return l.listener.localMultiaddrs[l.version]
+}
+
+func (l *virtualListener) Close() error {
+	l.acceptRunnner.RmAcceptForVersion(l.version)
+
+	l.t.listenersMu.Lock()
```
Comment (marten-seemann) [inline p2p/transport/quic/virtuallistener.go:34]: It would be nice if the `virutalListener` didn't have to interact with that much internal state of the transport. Can we move all this logic into a method on the transport?

**Review by marten-seemann — APPROVED** [review]
LGTM modulo the review comments here.

Can you add some tests similar to the one suggested in https://github.com/libp2p/go-libp2p/issues/1904#issue-1456706966 in `p2p/test`:
* create a draft-29 listener and check that a draft-29 connection is accepted, but a v1 connection is closed
* the other way round, for a v1 listener
* create a draft-29 + v1 listener and check that both versions are accepted
