### PR TITLE
fix: circuitv2: sanitize address inputs: check address peer id when returning a reservation message

### LINKED ISSUE #3003: Circuit relay reservation addresses sometimes returns with repeated relay PeerIds
If I make a relay reservation the `HopMessage.reservation.addrs` field  sometimes has multiaddrs that repeat the relay's peer id.

This only seems to happen with the WebSocket transport addresses advertised by the Amino DHT bootstrap nodes, so it might to AppendAnnounce addresses.  Nodes not listening on DNS/WSS addresses seem fine.

For example I make a reservation on `am6.bootstrap.libp2p.io`, PeerID `QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb`, these are the string versions of the `.addrs` field in the response `HopMessage`:

```
"/ip4/147.75.87.27/tcp/4001/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip4/147.75.87.27/udp/4001/webrtc-direct/certhash/uEiAWOyiAQrOpPuymJM2GnnXGQ4CmWIr8v1gV1v0kOfn3Yg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip4/147.75.87.27/udp/4001/webrtc-direct/certhash/uEiAWOyiAQrOpPuymJM2GnnXGQ4CmWIr8v1gV1v0kOfn3Yg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip4/147.75.87.27/udp/4001/quic-v1/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip4/147.75.87.27/udp/4001/quic-v1/webtransport/certhash/uEiBX-ETT3QF-2Ugo0sE7lZJkvrqVwltfSye-ghrf9pnPTg/certhash/uEiDLEI9-9k6c8VUdeQCgoyh1EdlRJN70EuCNnfagPe3Cqg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip4/147.75.87.27/udp/4001/quic-v1/webtransport/certhash/uEiBX-ETT3QF-2Ugo0sE7lZJkvrqVwltfSye-ghrf9pnPTg/certhash/uEiDLEI9-9k6c8VUdeQCgoyh1EdlRJN70EuCNnfagPe3Cqg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip6/2604:1380:4602:5c00::3/tcp/4001/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip6/2604:1380:4602:5c00::3/udp/4001/webrtc-direct/certhash/uEiAWOyiAQrOpPuymJM2GnnXGQ4CmWIr8v1gV1v0kOfn3Yg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip6/2604:1380:4602:5c00::3/udp/4001/webrtc-direct/certhash/uEiAWOyiAQrOpPuymJM2GnnXGQ4CmWIr8v1gV1v0kOfn3Yg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip6/2604:1380:4602:5c00::3/udp/4001/quic-v1/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip6/2604:1380:4602:5c00::3/udp/4001/quic-v1/webtransport/certhash/uEiBX-ETT3QF-2Ugo0sE7lZJkvrqVwltfSye-ghrf9pnPTg/certhash/uEiDLEI9-9k6c8VUdeQCgoyh1EdlRJN70EuCNnfagPe3Cqg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/ip6/2604:1380:4602:5c00::3/udp/4001/quic-v1/webtransport/certhash/uEiBX-ETT3QF-2Ugo0sE7lZJkvrqVwltfSye-ghrf9pnPTg/certhash/uEiDLEI9-9k6c8VUdeQCgoyh1EdlRJN70EuCNnfagPe3Cqg/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
"/dns6/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
```

They are all fine, except the final two `/dns4` and `/dns6` addresses which have the tuple `/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb` repeated twice.

These addresses are set by the `AppendAnnounce` config key.

I think this may be because the Circuit Relay spec says:

> the `addrs` field contains all the public relay addrs, including the peer ID of the relay node but not the trailing `p2p-circuit` part

"including the peer ID" is not something we do elsewhere (it's normally omitted from `PeerInfo`s received from the routing, for example), so I guess it's not checking if its PeerID is already present in the address before appending it?

### PR DESCRIPTION
**Pull request by MarcoPolo**
closes #3003

### CODE REVIEW

File: p2p/protocol/circuitv2/relay/relay.go [hunk 1]
```diff
@@ -567,31 +574,54 @@ func (r *Relay) writeResponse(s network.Stream, status pbv2.Status, rsvp *pbv2.R
...
+	selfP2PAddr, err := ma.NewComponent("p2p", selfID.String())
+	if err != nil {
+		log.Errorf("error creating p2p component: %s", err)
+		return rsvp
+	}
+
 	var addrBytes [][]byte
-	for _, addr := range r.host.Addrs() {
+	for _, addr := range selfAddrs {
 		if !manet.IsPublicAddr(addr) {
```
Comment (sukunrt) [inline p2p/protocol/circuitv2/relay/relay.go:596]: Why does `host.Addrs` return an address with P2P component?

**Review by sukunrt — APPROVED** [review]
