### PR TITLE
autonat: Clean up after close

### LINKED ISSUE #2743: AutoNAT fails to close its peerstore
The AutoNAT service creates a peerstore but fails to close it, leaking goroutines.

### PR DESCRIPTION
**Pull request by MarcoPolo**
Autonat would leave a couple of dangling go routines because it wouldn't close the swarm or the peerstore. Fixes #2743.

### CODE REVIEW

File: p2p/host/autonat/svc.go [hunk 1]
```diff
@@ -273,6 +273,11 @@ func (as *autoNATService) Disable() {
 	}
 }
 
+func (as *autoNATService) Close() error {
+	as.Disable()
+	return as.config.dialer.Close()
+}
+
```
Comment (sukunrt) [inline p2p/host/autonat/svc.go:280]: Should we just close the dialer from the autonat instance? That seems better, we ensure that the dialer is always closed even if for some reason there's an issue with service being set to nil for some reason. 
I don't have strong opinions here.

**Review by sukunrt — APPROVED** [review]

File: p2p/host/autonat/svc.go (hunk 1 above)
Comment (MarcoPolo) [reply p2p/host/autonat/svc.go:280]: My read here is that the dialer is owned by the service, so it's the service's responsibility to close it.
