### PR TITLE
fix: QUIC/Webtransport Transports now will prefer their owned listeners for dialing out

### LINKED ISSUE #2913: QUIC/WebTransport Transport sometimes uses the wrong socket to dial out.
### Context

Given the following scenario:
- Two peers: 
  - Peer A: with a public IP and a firewall blocking arbitrary remote connections. Running latest [Vole](https://github.com/ipfs-shipyard/vole)
  - Peer B (Kubo Node) behind NAT with a circuit relay reservation
- Peer A is running go-libp2p 0.36.1 as part of Vole
- Peer A is constructed with `h, err := libp2p.New(libp2p.DefaultMuxers, libp2p.EnableHolePunching())`
- Peer A is bound to a public IP
- The machine with Peer A has a firewall configured that blocks incoming connections on public interfaces, so even though `h.Addrs()` contains public IPs: 
  ```
  /ip4/127.0.0.1/tcp/35689 
  /ip4/127.0.0.1/udp/39191/webrtc-direct/certhash/uEiB5brq0KqYrJLT8O1Iq2Eo8E3gx8kThAJLs_pyncP74aA 
  /ip4/127.0.0.1/udp/39779/quic-v1/webtransport/certhash/uEiAvszmD8ETmRbFNmM1ZNPe1NDqJEGUSQku9xBhVR-n_MQ/certhash/uEiC9XsVxwVbJabPvDfAeooM4rrurb94qShBeDqmiS30Nfw 
  /ip4/127.0.0.1/udp/42886/quic-v1 
  /ip4/139.178.82.19/tcp/35689 
  /ip4/139.178.82.19/udp/39191/webrtc-direct/certhash/uEiB5brq0KqYrJLT8O1Iq2Eo8E3gx8kThAJLs_pyncP74aA 
  /ip4/139.178.82.19/udp/39779/quic-v1/webtransport/certhash/uEiAvszmD8ETmRbFNmM1ZNPe1NDqJEGUSQku9xBhVR-n_MQ/certhash/uEiC9XsVxwVbJabPvDfAeooM4rrurb94qShBeDqmiS30Nfw 
  /ip4/139.178.82.19/udp/42886/quic-v1 
  /ip6/::1/tcp/39833 
  /ip6/::1/udp/42162/quic-v1 
  /ip6/::1/udp/46915/quic-v1/webtransport/certhash/uEiAvszmD8ETmRbFNmM1ZNPe1NDqJEGUSQku9xBhVR-n_MQ/certhash/uEiC9XsVxwVbJabPvDfAeooM4rrurb94qShBeDqmiS30Nfw 
  /ip6/::1/udp/59420/webrtc-direct/certhash/uEiB5brq0KqYrJLT8O1Iq2Eo8E3gx8kThAJLs_pyncP74aA 
  /ip6/2604:1380:4642:6600::1/tcp/39833 
  /ip6/2604:1380:4642:6600::1/udp/42162/quic-v1 
  /ip6/2604:1380:4642:6600::1/udp/46915/quic-v1/webtransport/certhash/uEiAvszmD8ETmRbFNmM1ZNPe1NDqJEGUSQku9xBhVR-n_MQ/certhash/uEiC9XsVxwVbJabPvDfAeooM4rrurb94qShBeDqmiS30Nfw 
  /ip6/2604:1380:4642:6600::1/udp/59420/webrtc-direct/certhash/uEiB5brq0KqYrJLT8O1Iq2Eo8E3gx8kThAJLs_pyncP74aA]
  ```
  they are not dialable

## Problem

- Hole punching between the will fail consistently, because Peer A will not have the `/libp2p/dcutr` protocol enabled. 
- This causes a stream reset (logged by Peer A) and the `"error": "failed to open hole-punching stream: failed to negotiate protocol: protocols not supported: [/libp2p/dcutr]"}` error (logged by Peer B).

## Source of the problem

Based on debugging with @sukunrt, it appears to be related to the following lines:
- https://github.com/libp2p/go-libp2p/blob/16a27ff08cfda4ec780e6dd69e178a2031adbeab/p2p/protocol/holepunch/svc.go#L109
- https://github.com/libp2p/go-libp2p/blob/16a27ff08cfda4ec780e6dd69e178a2031adbeab/p2p/protocol/holepunch/svc.go#L174

We were able to work around this problem and successfully hole punch by replacing `s.ids.OwnObservedAddrs()` with `s.host.Addrs())`. This was a temporary measure, as we may just want to **add** the listen addrs to the observed addrs. 

## Related issue

- https://github.com/ipfs-shipyard/ipfs-check/issues/40

### PR DESCRIPTION
**Pull request by MarcoPolo**
Fixes #2913 

The issue is presented in https://github.com/libp2p/go-libp2p/issues/2913#issuecomment-2305818394.

The fix here introduces "associations" to refcountedTransports. a libp2p transport can associate itself with the transport used for listening, and then prefer to use that for dialing by passing itself as the association.

### CODE REVIEW

File: p2p/transport/webtransport/listener.go [hunk 1]
```diff
@@ -295,5 +299,15 @@ loop:
 			break loop
 		}
 	}
+
+	l.transport.listenersMu.Lock()
+	for i, ln := range l.transport.listeners {
+		if ln == l {
+			l.transport.listeners = append(l.transport.listeners[:i], l.transport.listeners[i+1:]...)
```
Comment (sukunrt) [inline p2p/transport/webtransport/listener.go:306]: you can use `slices.DeleteFunc`

File: p2p/transport/webtransport/transport.go [hunk 2]
```diff
@@ -207,10 +231,28 @@ func (t *transport) dial(ctx context.Context, addr ma.Multiaddr, url, sni string
...
+		clientConf.AllowConnectionWindowIncrease = t.allowWindowIncrease
+		naddr, _, err := quicreuse.FromQuicMultiaddr(addr)
+		if err != nil {
+			return nil, nil, err
+		}
+
+		conn, err = listener.reuseListener.Dial(ctx, naddr, tlsConf, clientConf)
+		if err != nil {
+			return nil, nil, err
+		}
```
Comment (sukunrt) [inline p2p/transport/webtransport/transport.go:248]: Should we expose this as a method in `ConnManager` as `DialWithListener` or `DialWithTransport` or something. I am specifically interested in keeping this logic in one place. 

```
clientConf := t.connManager.ClientConfig().Clone()
clientConf.AllowConnectionWindowIncrease = t.allowWindowIncrease
naddr, _, err := quicreuse.FromQuicMultiaddr(addr)
if err != nil {
	return nil, nil, err
}
```

File: p2p/transport/quic/transport.go [hunk 3]
```diff
@@ -129,16 +129,56 @@ func (t *transport) Dial(ctx context.Context, raddr ma.Multiaddr, p peer.ID) (_c
...
+		return nil, err
+	}
+	t.listenersMu.Lock()
+	defer t.listenersMu.Unlock()
+	for _, ls := range t.listeners {
+		for _, l := range ls {
+			lnetw, _, err := manet.DialArgs(l.Multiaddr())
+			if err != nil {
+				continue
+			}
```
Comment (sukunrt) [inline p2p/transport/quic/transport.go:146]: should we log this?

File: libp2p_test.go [hunk 4]
```diff
@@ -587,3 +588,61 @@ func TestWebRTCReuseAddrWithQUIC(t *testing.T) {
 		require.Contains(t, h1.Addrs()[0].String(), "quic-v1")
 	})
 }
+
+func TestUseCorrectTransportForDialOut(t *testing.T) {
+	listAddrOrder := [][]string{
+		{"/ip4/127.0.0.1/udp/0/quic-v1", "/ip4/127.0.0.1/udp/0/quic-v1/webtransport"},
+		{"/ip4/127.0.0.1/udp/0/quic-v1/webtransport", "/ip4/127.0.0.1/udp/0/quic-v1"},
+	}
```
Comment (sukunrt) [inline libp2p_test.go:596]: Can you add a test case for Listening on `0.0.0.0` too?

**Review by sukunrt — APPROVED** [review]

File: p2p/transport/webtransport/transport.go (hunk 2 above)
Comment (MarcoPolo) [reply p2p/transport/webtransport/transport.go:248]: It would be a small benefit for reducing reuse here, but at the expense of introducing a new public method in ConnManager. If ConnManager was internal, I think that would be okay. But I don't think the reuse here is worth the tradeoff.

**Comment by MarcoPolo** [comment]
I think there's an issue here where we don't have any logic to pick the interface that can actually route the packet.

**Comment by MarcoPolo** [comment]
I've changed this PR completely. I think it's a little cleaner now. Minimal changes to the transports, and leveraging existing logic in the quicreuse package.

Another review please @sukunrt ?

**Review by sukunrt — APPROVED** [review]
This is definitely nicer. Thanks!

**Comment by ethan-gallant** [comment]
@MarcoPolo I think this may have broken hole punching as it seems to prefer the port which the relay signaled on opposed to the higher available hole punch ports.

**Comment by ethan-gallant** [comment]
Notably removing this line resolves the issue where it tries to establish the hole punch from the origin port `443` even though that port is filtered out in the local and remote available addresses for the punch.

https://github.com/libp2p/go-libp2p/blob/0fde4dcb01d83117495f0c920c34c8f540467d4c/p2p/transport/webtransport/transport.go#L210

**Comment by MarcoPolo** [comment]
@ethan-gallant, can you please open an issue here and outline what your setup is? I don't want this to get lost. Thanks!
