### PR TITLE
fix: clean up associations for closed listeners.

### LINKED ISSUE #3246: Clean up associations in quicreuse when a listener is closed
We associate a transport when [listening](https://github.com/libp2p/go-libp2p/blob/1f6232db191f07c4de212dea7b7fa13fb524ddc6/p2p/transport/quicreuse/connmgr.go#L184), but we aren't cleaning up the association when the listener is closed.

### PR DESCRIPTION
**Pull request by Prabhat1308**
fixes #3246 

~- adds tracking of listener associations with a listenerID~ 
- removes associations of the closed listener from the map
- adds test for scenarios of single and multiple listener cleanups

### CODE REVIEW

**Comment by Prabhat1308** [comment]
Interoperability tests failure is unrelated

File: p2p/transport/quicreuse/connmgr.go [hunk 1]
```diff
@@ -68,6 +70,9 @@ type ConnManager struct {
 	connContext connContextFunc
 
 	verifySourceAddress func(addr net.Addr) bool
+
+	// Counter for generating unique listener IDs within this ConnManager instance
+	listenerIDCounter uint64
```
Comment (sukunrt) [inline p2p/transport/quicreuse/connmgr.go]: I don't think we need this.

File: p2p/transport/quicreuse/reuse.go [hunk 2]
```diff
@@ -106,7 +108,30 @@ func (c *refcountedTransport) associate(a any) {
 	if c.assocations == nil {
 		c.assocations = make(map[any]struct{})
 	}
+	if c.listenerAssociations == nil {
+		c.listenerAssociations = make(map[string][]any)
+	}
 	c.assocations[a] = struct{}{}
```
Comment (sukunrt) [inline p2p/transport/quicreuse/reuse.go]: You can store the associations with the listener here in the map. `map[any]map[listener]struct{}` And then remove the association on listener close. Even a list of listeners is fine `map[any][]listeners`

File: p2p/transport/quicreuse/reuse.go [hunk 3]
```diff
@@ -106,7 +108,30 @@ func (c *refcountedTransport) associate(a any) {
...
+	c.listenerAssociations[listenerKey] = append(c.listenerAssociations[listenerKey], a)
+}
+
+// disassociateListener removes ALL associations added by a specific listener
+func (c *refcountedTransport) disassociateListener(listenerKey string) {
```
Comment (sukunrt) [inline p2p/transport/quicreuse/reuse.go]: `RemoveAssociationsForListener(ln listener)`

File: p2p/transport/quicreuse/reuse.go (hunk 2 above)
Comment (sukunrt) [reply p2p/transport/quicreuse/reuse.go]: If you want the reverse mapping for removal you can store it in a separate map `map[listener]any`. But iteration over all associations is also fine, it has 10 elements at max.

**Comment by sukunrt** [comment]
Thanks for tackling this @Prabhat1308

**Comment by Prabhat1308** [comment]
addressed the comments in [`7d09709`](https://github.com/libp2p/go-libp2p/pull/3306/commits/7d09709ded0db53f0e7b5f7e7ede873624e11ef4)

File: p2p/transport/quicreuse/connmgr.go [hunk 4]
```diff
@@ -243,28 +244,42 @@ func (c *ConnManager) ListenQUICAndAssociate(association any, addr ma.Multiaddr,
 		if err != nil {
 			return nil, fmt.Errorf("reuse assert transport failed: %w", err)
 		}
-		if tr, ok := entry.ln.transport.(*refcountedTransport); ok {
-			tr.associate(association)
-		}
 	}
-	l, err := entry.ln.Add(tlsConf, allowWindowIncrease, func() { c.onListenerClosed(key) })
+	var l Listener
+	l, err = entry.ln.Add(tlsConf, allowWindowIncrease, func() {
```
Comment (sukunrt) [inline p2p/transport/quicreuse/connmgr.go]: I prefer doing it like this: 
Change the signature of this method to 
```
func (l *quicListener) Add(association any, tlsConf *tls.Config, allowWindowIncrease func(conn quic.Connection, delta uint64) bool, onRemove func()) (*listener, error) {
```

And within the `Add` method, remove the `newSingleListener` func and do something like this: 

```
	ln := &listener{
		queue:             make(chan quic.Connection, queueLen),
		acceptLoopRunning: l.running,
		addr:              l.l.Addr(),
		addrs:             l.addrs,
	}
	if association != nil {
		if tr, ok := l.transport.(*refcountedTransport); ok {
			tr.associateForListener(association, ln)
		}
	}

	ln.remove = func() {
		if association != nil {
			if tr, ok := l.transport.(*refcountedTransport); ok {
				tr.RemoveAssociationsForListener(ln)
			}
		}
		l.protocolsMu.Lock()
		for _, proto := range tlsConf.NextProtos {
			delete(l.protocols, proto)
		}
		l.protocolsMu.Unlock()
		onRemove()
	}
```

This ensures that adding and removing are done together, and at the spot the listener to be associated is created. All single protocol listener creation codepaths will go through `Add`. 

Also avoids the type casting.

File: p2p/transport/quicreuse/connmgr.go [hunk 5]
```diff
@@ -306,7 +321,7 @@ func (c *ConnManager) transportForListen(association any, network string, laddr
 		if err != nil {
 			return nil, err
 		}
-		tr.associate(association)
+		// Association will be handled in ListenQUICAndAssociate with the proper listener key
```
Comment (sukunrt) [inline p2p/transport/quicreuse/connmgr.go]: remove this comment. As there's no association, it's unlikely that future readers will get confused by the removal of associations here.

File: p2p/transport/quicreuse/connmgr_test.go [hunk 6]
```diff
@@ -489,3 +489,155 @@ func TestConnContext(t *testing.T) {
 		})
 	}
 }
+
+func TestAssociationCleanup(t *testing.T) {
```
Comment (sukunrt) [inline p2p/transport/quicreuse/connmgr_test.go:493]: I don't like these two tests since they're asserting on internal state. 

You can use this testcase. Modify it however you like. 

```
func TestAssociationCleanup(t *testing.T) {
	cm, err := NewConnManager(quic.StatelessResetKey{}, quic.TokenGeneratorKey{})
	require.NoError(t, err)
	defer cm.Close()

	// Create 3 listeners with 3 different associations
	lp2pTLS := &tls.Config{NextProtos: []string{"libp2p"}}
	assoc1 := "test-association-1"
	assoc2 := "test-association-2"
	assoc3 := "test-association-3"

	ln1, err := cm.ListenQUICAndAssociate(assoc1, ma.StringCast("/ip4/127.0.0.1/udp/0/quic-v1"), lp2pTLS, nil)
	require.NoError(t, err)
	defer ln1.Close()

	ln2, err := cm.ListenQUICAndAssociate(assoc2, ma.StringCast("/ip4/127.0.0.1/udp/0/quic-v1"), lp2pTLS, nil)
	require.NoError(t, err)
	defer ln2.Close()

	ln3, err := cm.ListenQUICAndAssociate(assoc3, ma.StringCast("/ip4/127.0.0.1/udp/0/quic-v1"), lp2pTLS, nil)
	require.NoError(t, err)
	defer ln3.Close()

	// Get the listen addresses for verification
	addr1 := ln1.Addr().String()
	addr2 := ln2.Addr().String()
	addr3 := ln3.Addr().String()

	// Test that dialing with assoc1 uses the first listener's address
	dialAddr := &net.UDPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 1234}

	for i := 0; i < 10; i++ {
		tr, err := cm.TransportWithAssociationForDial(assoc1, "udp4", dialAddr)
		require.NoError(t, err)
		require.Equal(t, addr1, tr.LocalAddr().String(), "assoc1 should use addr1")
	}

	// Close the first listener
	ln1.Close()

	// Call TransportWithAssociationForDial 10 times with assoc1 and check if we get at least one different address
	foundDifferentAddr := false
	for i := 0; i < 10; i++ {
		tr, err := cm.TransportWithAssociationForDial(assoc1, "udp4", dialAddr)
		require.NoError(t, err)
		actualAddr := tr.LocalAddr().String()
		if actualAddr != addr1 {
			foundDifferentAddr = true
			break
		}
	}
	require.True(t, foundDifferentAddr, "assoc1 should use a different address than addr1 at least once after ln1 is closed")

	for i := 0; i < 10; i++ {
		// Test that dialing with assoc2 still uses the second listener's address
		tr2Still, err := cm.TransportWithAssociationForDial(assoc2, "udp4", dialAddr)
		require.NoError(t, err)
		require.Equal(t, addr2, tr2Still.LocalAddr().String(), "assoc2 should still use addr2")
	}

	// Close the second listener
	ln2.Close()

	// Call TransportWithAssociationForDial 10 times with assoc2 and check if we get at least one different address
	foundDifferentAddr2 := false
	for i := 0; i < 10; i++ {
		tr, err := cm.TransportWithAssociationForDial(assoc2, "udp4", dialAddr)
		require.NoError(t, err)
		actualAddr := tr.LocalAddr().String()
		if actualAddr != addr2 {
			foundDifferentAddr2 = true
		}
	}
	require.True(t, foundDifferentAddr2, "assoc2 should use a different address than addr2 at least once after ln2 is closed")

	for i := 0; i < 10; i++ {
		// Test that dialing with assoc3 still uses the third listener's address
		tr3Still, err := cm.TransportWithAssociationForDial(assoc3, "udp4", dialAddr)
		require.NoError(t, err)
		require.Equal(t, addr3, tr3Still.LocalAddr().String(), "assoc3 should still use addr3")
		tr3Still.Close()
	}
}
```

**Comment by sukunrt** [comment]
Thanks @Prabhat1308. I think we can merge this after these changes. This code is very tricky.

File: p2p/transport/quicreuse/connmgr.go (hunk 4 above)
Comment (Prabhat1308) [reply p2p/transport/quicreuse/connmgr.go]: done.

File: p2p/transport/quicreuse/connmgr.go (hunk 5 above)
Comment (Prabhat1308) [reply p2p/transport/quicreuse/connmgr.go]: done

File: p2p/transport/quicreuse/connmgr_test.go (hunk 6 above)
Comment (Prabhat1308) [reply p2p/transport/quicreuse/connmgr_test.go:493]: replaced the 2 association tests .

**Comment by sukunrt** [comment]
Thanks @Prabhat1308
