### PR TITLE
autorelay: fix busy loop bug and flaky tests in relay finder

### LINKED ISSUE #2189: autorelay: Handle WithMinInterval(0) without constantly looping
If we initialise autorelay with WithMinInterval(0) that causes the background go routine to go into a spin loop. 
https://github.com/libp2p/go-libp2p/blob/master/p2p/host/autorelay/relay_finder.go#L225-L230
here the scheduledTime for next allowed call will always be current time and the scheduledWorkTimer fires immediately. 

kubo currently uses MinInterval(0)
https://github.com/ipfs/kubo/blob/a3366c522a578db610d8633c5a15ebddb6e96e39/core/node/libp2p/relay.go#L101

### PR DESCRIPTION
**Pull request by MarcoPolo**
Also adds our own custom mock clock that fits a better interface for this module.

The new mock clock implements the following interface:
```go
// InstantTimer is a timer that triggers at some instant rather than some duration
type InstantTimer interface {
	Reset(d time.Time) bool
	Stop() bool
	Ch() <-chan time.Time
}

// ClockWithInstantTimer is a clock that can create timers that trigger at some
// instant rather than some duration
type ClockWithInstantTimer interface {
	Now() time.Time
	Since(t time.Time) time.Duration
	InstantTimer(when time.Time) InstantTimer
}
```

This lets us avoid the issue of https://github.com/libp2p/go-libp2p/pull/2187 altogether.

The new mock clock is about 100 LOC and should behave logically close to a real clock (time shouldn't jump from 0 to 1000 without work being done in between).

Closes #2187. Closes #2192. Fixes #2189. Closes #2183 

I chose to incorporate those PRs into this one to avoid the merge conflicts that would ensue.

### CODE REVIEW

File: p2p/host/autorelay/autorelay_test.go [hunk 1]
```diff
@@ -294,8 +296,122 @@ func TestConnectOnDisconnect(t *testing.T) {
...
 
+type mockClock struct {
+	mu     sync.Mutex
+	now    time.Time
+	timers []*mockInstantTimer
+}
+
+var _ autorelay.ClockWithInstantTimer = &mockClock{}
+
+type mockInstantTimer struct {
```
Comment (marten-seemann) [inline p2p/host/autorelay/autorelay_test.go:307]: Move this to a separate file? We might need this at other places as well, and that makes it easier to expose later without losing Git history.

File: p2p/host/autorelay/autorelay_test.go [hunk 2]
```diff
@@ -294,8 +296,122 @@ func TestConnectOnDisconnect(t *testing.T) {
...
+	return c.now.Sub(t)
+}
+
+func (c *mockClock) Now() time.Time {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+	return c.now
+}
+
+func (c *mockClock) advanceBy(dur time.Duration) {
```
Comment (marten-seemann) [inline p2p/host/autorelay/autorelay_test.go:376]:
```suggestion
func (c *mockClock) AdvanceBy(dur time.Duration) {
```

File: p2p/host/autorelay/relay_finder.go [hunk 3]
```diff
@@ -128,32 +132,36 @@ func (rf *relayFinder) background(ctx context.Context) {
...
+	if rf.conf.maxCandidateAge > leastFrequentInterval || leastFrequentInterval == 0 {
 		leastFrequentInterval = rf.conf.maxCandidateAge
 	}
-	if rsvpRefreshInterval > leastFrequentInterval {
-		leastFrequentInterval = rf.conf.maxCandidateAge
+	if rsvpRefreshInterval > leastFrequentInterval || leastFrequentInterval == 0 {
+		leastFrequentInterval = rsvpRefreshInterval
+	}
+	if leastFrequentInterval == 0 {
+		// fallback to avoid busy looping in case the config is set to all 0s
```
Comment (marten-seemann) [inline p2p/host/autorelay/relay_finder.go:152]: `rsvpRefreshInterval` is a constant (1 minute), so this is not possible, right?

File: core/test/mockclock.go
Comment (marten-seemann) [inline core/test/mockclock.go:1]: Oh nice, you already extracted it to a separate package.

File: p2p/host/autorelay/relay_finder.go [hunk 4]
```diff
@@ -128,32 +132,32 @@ func (rf *relayFinder) background(ctx context.Context) {
...
 
-	now := rf.conf.clock.Now()
-
 	scheduledWork := &scheduledWorkTimes{
 		leastFrequentInterval:       leastFrequentInterval,
 		nextRefresh:                 now.Add(rsvpRefreshInterval),
-		nextBackoff:                 now.Add(rf.conf.backoff / 5),
-		nextOldCandidateCheck:       now.Add(rf.conf.maxCandidateAge / 5),
+		nextBackoff:                 now.Add(rf.conf.backoff),
+		nextOldCandidateCheck:       now.Add(rf.conf.maxCandidateAge),
```
Comment (marten-seemann) [inline p2p/host/autorelay/relay_finder.go:156]: Is this correct? I thought the 5 was so we don't add up with lists that are completely outdated. Reminder to self: document every magic number.

Comment (marten-seemann) [reply p2p/host/autorelay/relay_finder.go:156]: I've convinced myself that this isn't needed any more.

**Review by marten-seemann — APPROVED** [review]
