### PR TITLE
correctly handle WebTransport addresses without certhashes

### LINKED ISSUE #2223: Cannot advertise WebTransport with externally known addresses (external static IP + port forwarding, dns, etc.)
When running a go-libp2p host behind a NAT with port forwarding enabled or another environment where the user might know more about the addresses to advertise than go-libp2p has been able to discover (e.g. DNS addresses) users pass in their addresses via the `AddrsFactory` option https://github.com/libp2p/go-libp2p/blob/8c466ab7f8d0e1eb12ea8a23933e77d25190a81a/options.go#L260

As I understand it the `AddrsFactory` takes in the list of addresses that go-libp2p thinks it should be advertising and then allows the user to modify that list (e.g. override/remove elements, add new ones, etc.). The multiaddrs processed and returned by this function are ones that do not have the `/p2p/<peerID>` suffix.

Unfortunately, this behavior doesn't work for WebTransport since naively adding an additional `/ip4/1.2.3.4/udp/1234/quic-v1/webtransport` will be broken due to the lack of WebTransport certificates that are not added internally by go-libp2p. This is not something the user can reasonably deal with by passing the certificates themselves without understanding (and replicating) the internal go-libp2p mechanism for managing WebTransport certificates (having deterministic certificates generated with timestamps based on dividing time into fixed intervals) or finding some awkward workaround (e.g. having a loopback webtransport listener and then reading the certificates go-libp2p has emitted for the loopback listener and feeding it back into the `AddrsFactory`).

### LINKED ISSUE #2233: Cannot advertise WebTransport with public IP addresses discovered by identify (e.g. port forwarding behind a NAT with a dynamic public IP)
I haven't repro'd this myself yet, but we should investigate and add a test case for this.

### PR DESCRIPTION
**Pull request by MarcoPolo**
Fixes #2233. Closes #2227. Fixes #2223.

### CODE REVIEW

File: p2p/host/basic/basic_host.go [hunk 1]
```diff
@@ -760,7 +763,48 @@ func (h *BasicHost) ConnManager() connmgr.ConnManager {
...
+		}
+	}
+	return addrs
+}
+
+// NormalizeMultiaddr returns a multiaddr suitable for equality checks.
+// If the multiaddr is a webtransport component, it removes the certhashes.
+func (h *BasicHost) NormalizeMultiaddr(addr ma.Multiaddr) ma.Multiaddr {
+	if ok, n := libp2pwebtransport.IsWebtransportMultiaddr(addr); ok && n > 0 {
+		var firstCerthash ma.Multiaddr
```
Comment (MarcoPolo) [inline p2p/host/basic/basic_host.go:797]: I don't like this. @marten-seemann If you have a better idea here, I'm all ears.

File: options.go [hunk 2]
```diff
@@ -262,6 +262,7 @@ func AddrsFactory(factory config.AddrsFactory) Option {
 		if cfg.AddrsFactory != nil {
 			return fmt.Errorf("cannot specify multiple address factories")
 		}
+
```
Comment (marten-seemann) [inline options.go:265]:
```suggestion

```

File: p2p/host/basic/basic_host.go (hunk 1 above)
Comment (MarcoPolo) [reply p2p/host/basic/basic_host.go]: nvm, I forgot about SplitLast.

File: p2p/host/basic/basic_host.go [hunk 3]
```diff
@@ -760,7 +763,48 @@ func (h *BasicHost) ConnManager() connmgr.ConnManager {
...
+			}
+			addrs[i] = tpt.AddCertHashes(addr)
+		}
+	}
+	return addrs
+}
+
+// NormalizeMultiaddr returns a multiaddr suitable for equality checks.
+// If the multiaddr is a webtransport component, it removes the certhashes.
+func (h *BasicHost) NormalizeMultiaddr(addr ma.Multiaddr) ma.Multiaddr {
```
Comment (marten-seemann) [inline p2p/host/basic/basic_host.go:794]: I assume this would move into the address pipeline, once we have it, right?

File: p2p/host/basic/basic_host.go (hunk 1 above)
Comment (marten-seemann) [reply p2p/host/basic/basic_host.go]: `ma.SplitFunc`?

File: p2p/host/basic/basic_host.go [hunk 4]
```diff
@@ -760,7 +762,44 @@ func (h *BasicHost) ConnManager() connmgr.ConnManager {
 // Addrs returns listening addresses that are safe to announce to the network.
 // The output is the same as AllAddrs, but processed by AddrsFactory.
 func (h *BasicHost) Addrs() []ma.Multiaddr {
-	return h.AddrsFactory(h.AllAddrs())
+	type transportForListeninger interface {
```
Comment (marten-seemann) [inline p2p/host/basic/basic_host.go:765]: Add a comment that this is a hack, linking to the respective issue?

**Review by marten-seemann — APPROVED** [review]

File: p2p/host/basic/basic_host.go (hunk 3 above)
Comment (MarcoPolo) [reply p2p/host/basic/basic_host.go:794]: Sure! Anywhere that isn't adding another method to BasicHost

**Review by marten-seemann — APPROVED** [review]
