### PR TITLE
autonat: fix flaky TestAutoNATPrivate 

### LINKED ISSUE #1566: autonat: flaky TestAutoNATPrivate
```
  === RUN   TestAutoNATPrivate
      autonat_test.go:122: 
          	Error Trace:	autonat_test.go:122
          	Error:      	Condition never satisfied
          	Test:       	TestAutoNATPrivate
          	Messages:   	expected NAT status to be private
  --- FAIL: TestAutoNATPrivate (2.08s)

### PR DESCRIPTION
**Pull request by MarcoPolo**
Fixes #1566 by scaling duration 3/2x. Waits on a channel.

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

File: p2p/host/autonat/autonat_test.go [hunk 1]
```diff
@@ -121,8 +122,8 @@ func TestAutoNATPrivate(t *testing.T) {
 	connect(t, hs, hc)
 	require.Eventually(t,
 		func() bool { return an.Status() == network.ReachabilityPrivate },
-		2*time.Second,
-		25*time.Millisecond,
+		testutils.ScaleDuration(2*time.Second),
```
Comment (marten-seemann) [inline p2p/host/autonat/autonat_test.go:125]: Any idea why this takes so long? I would've expected 2s to be a long timeout already.

Comment (marten-seemann) [reply p2p/host/autonat/autonat_test.go]: I think it's this second: https://github.com/libp2p/go-libp2p/blob/e732bda3fa076707e2837eb9edfe8955ee8f4ad8/p2p/host/autonat/autonat.go#L256-L262. The first timer fires immediately, but doesn't have any peer ID yet. The second timer fires after one second.

Seems like 20s is way too much on CI. Maybe we can just set to 3s?

Comment (MarcoPolo) [reply p2p/host/autonat/autonat_test.go]: It's the upper limit, but sure updated :)

**Review by marten-seemann — APPROVED** [review]
