### PR TITLE
swarm: fix DialPeer behaviour for transient connections

### LINKED ISSUE #1603: Connect should wait for an acceptable connection
Currently, it waits for _any_ connection, then returns. Unfortunately, this means that if the user calls `host.NewStream(peer)` to try to get a new stream to a non-connected peer, we'll _fail_ every single time if we try to create a stream behind a NAT.

The difficulty here is that we aren't "in control", and don't know if the remote peer will actually directly connect to us. It's up to the _receiver_ to establish a direct connection.

I think the solution here is to wait a bit after we establish a transient connection to see if a non-transient connection comes through. The tricky part will be actually _implementing_ that...

### PR DESCRIPTION
**Pull request by sukunrt**
This fixes a bug where the first call to `swarm.DialPeer` succeeds and returns a transient connection with no error while the second call to `swarm.DialPeer` returns `(nil, network.ErrTransientConn)`.

For dialing, we now only rely on `network.WithForceDirectDial` to force a direct connection.
For new stream, we open a stream on a transient connection only if `network.WithUseTransient` is used.

This feels correct to me since once we fix #1603 we can have `NewStream` called without `network.WithUseTransient` or `network.WithForceDirectDial` and it'll wait for the transient connection to be upgraded to a direct connection before returning.  

I'm not fixing it the other way round, i.e. Failing if `network.WithUseTransient` is not used, because there are users of this API who are probably relying on the first call to succeed. https://github.com/search?q=Network%28%29.DialPeer&type=code

### CODE REVIEW

File: p2p/test/swarm/swarm_test.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+	h1.Peerstore().AddAddr(h2.ID(), relayaddr, peerstore.TempAddrTTL)
+
+	// swarm.DialPeer should connect over transient connections
+	conn1, err := h1.Network().DialPeer(context.Background(), h2.ID())
+	require.NoError(t, err)
+	require.NotNil(t, conn1)
+
+	conn2, err := h1.Network().DialPeer(context.Background(), h2.ID())
+	require.NoError(t, err)
+	require.NotNil(t, conn2)
```
Comment (sukunrt) [inline p2p/test/swarm/swarm_test.go:68]: On current master, the first call succeeds while the second one fails.

File: p2p/net/swarm/swarm.go [hunk 2]
```diff
@@ -548,26 +546,17 @@ func (s *Swarm) bestConnToPeer(p peer.ID) *Conn {
 	return best
 }
 
-// - Returns the best "acceptable" connection, if available.
-// - Returns nothing if no such connection exists, but if we should try dialing anyways.
-// - Returns an error if no such connection exists, but we should not try dialing.
-func (s *Swarm) bestAcceptableConnToPeer(ctx context.Context, p peer.ID) (*Conn, error) {
+// bestAcceptableConnToPeer returns the best acceptable connection in the ctx passed. If
+// network.WithForceDirectDial is used, it'll only returns a direct connection ignoring
+// any transient(relayed) connections to the peer.
```
Comment (marten-seemann) [inline p2p/net/swarm/swarm.go:551]:
```suggestion
// bestAcceptableConnToPeer returns the best acceptable connection, considering the passed in ctx.
// If network.WithForceDirectDial is used, it only returns a direct connections, ignoring
// any transient (relayed) connections to the peer.
```

File: p2p/test/swarm/swarm_test.go [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+	relayaddr := ma.StringCast("/p2p/" + relay1info.ID.String() + "/p2p-circuit/p2p/" + h2.ID().String())
+
+	h1.Peerstore().AddAddr(h2.ID(), relayaddr, peerstore.TempAddrTTL)
+
+	// swarm.DialPeer should connect over transient connections
+	conn1, err := h1.Network().DialPeer(context.Background(), h2.ID())
+	require.NoError(t, err)
+	require.NotNil(t, conn1)
+
+	conn2, err := h1.Network().DialPeer(context.Background(), h2.ID())
```
Comment (marten-seemann) [inline p2p/test/swarm/swarm_test.go:58]:
```suggestion
	// Test that repeated calls return the same connection.
	conn2, err := h1.Network().DialPeer(context.Background(), h2.ID())
```

File: p2p/net/swarm/swarm.go [hunk 4]
```diff
@@ -428,7 +428,8 @@ func (s *Swarm) StreamHandler() network.StreamHandler {
 }
 
 // NewStream creates a new stream on any available connection to peer, dialing
-// if necessary.
+// if necessary. Use network.WithUseTransient to open a stream over a transient(relayed)
+// connection.
```
Comment (marten-seemann) [inline p2p/net/swarm/swarm.go:432]:
```suggestion
// if necessary.
// Use network.WithUseTransient to open a stream over a transient (relayed) connection.
```

**Review by marten-seemann — APPROVED** [review]

File: p2p/net/swarm/swarm.go (hunk 2 above)
Comment (sukunrt) [reply p2p/net/swarm/swarm.go]: thanks. This reads much better.

**Review by marten-seemann — APPROVED** [review]
